name: Infra Container
run-name: "${{ github.actor }}"

on: [ push ]

jobs:
    terraform-jobs:
        runs-on: ubuntu-latest
        container:
            image: hashicorp/terraform:1.7.0
            env:
                # Usamos la ruta absoluta estándar de GitHub Actions dentro de contenedores
                GCP_JSON_KEY: ${{ secrets.GCP_SA_TERRAFORM }}
                GOOGLE_APPLICATION_CREDENTIALS: /github/workspace/gcp-key.json
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            # PASO CORREGIDO: Usamos la ruta absoluta para asegurar que el archivo esté donde dice la variable
            - name: Create Credentials File
              run: echo "$GCP_JSON_KEY" > /github/workspace/gcp-key.json

            - name: Check Version
              run: terraform --version

            - name: Terraform init
              run: terraform init 

            - name: Create tfvars
              run: |
                cat <<EOF > terraform.tfvars
                project_name    = "opensip-prod"
                region_name     = "us-central1"
                bucket_name     = "git_hub_test_container"
                location_name   = "us-central1"
                EOF

            - name: Terraform Plan
              run: terraform plan -out=tfplan -input=false

            - name: Terraform apply
              if: github.ref == 'refs/heads/master'
              # CORREGIDO: Cambiado 'ftplan' por 'tfplan'
              run: terraform apply -auto-approve tfplan