name: Infra Container
run-name: "${{ github.actor }}"

on: 
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      action:
        description: 'write "destroy" to delete all resources'
        required: false
        default: 'apply'

#concurrency checkout
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    terraform-jobs:
        runs-on: ubuntu-latest
        container:
            image: hashicorp/terraform:1.7.0
            env:
                GCP_JSON_KEY: ${{ secrets.GCP_SA_TERRAFORM }}
                # 1. Usamos una ruta relativa simple. Terraform la entenderá perfecto.
                GOOGLE_APPLICATION_CREDENTIALS: ./gcp-key.json
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            # 2. CREACIÓN DEL ARCHIVO: Usamos el nombre directo sin rutas largas.
            # El archivo se creará justo donde está tu código.
            - name: Create Credentials File
              run: echo "$GCP_JSON_KEY" > gcp-key.json

            - name: Check Version
              run: terraform --version

            - name: Terraform init
              run: terraform init 

            - name: Create tfvars
              run: |
                cat <<EOF > terraform.tfvars
                project_name    = "opensip-prod"
                region_name     = "us-central1"
                bucket_name     = "git_hub_test_container"
                location_name   = "us-central1"
                EOF

            - name: Terraform Plan
              id: plan
              run: |
                ACTION=$(echo "${{ github.event.inputs.action }}" | xargs | tr '[:upper:]' '[:lower:]')
                if [ "$ACTION" == "destroy" ]; then
                  echo "build destroy plan"
                  terraform plan -destroy -out=tfplan -input=false
                else
                  echo "build deployment plant"
                  terraform plan -out=tfplan -input=false
                fi

            - name: Terraform apply
              if: github.ref == 'refs/heads/master'
              run: terraform apply -auto-approve tfplan
            
          